%% import_gmx_energy.m
% * This function imports all the average values generated by gmx energy
% the MD package Gromacs uses for some of its text-based data output
%
%% Version
% 3.00
%
%% Contact
% Please report problems/bugs to michael.holmboe@umu.se
%
%% Examples
% First run gmx energy with something like this:
% !echo {1..50} | gmx energy -f opt.edr > results.dat # Will import all items 1 to 50
% #  Data = import_xvg('results.dat')
%
function data = import_gmx_energy(filename)

% Open the file for reading
fid = fopen(filename, 'rt');
if fid == -1
    error('Cannot open file: %s', filename);
end

data = struct(); % Initialize an empty struct

% Read the file line by line
while ~feof(fid)
    line = fgetl(fid);

    % Skip until the line of "-----"
    if startsWith(line, '-----')
        break; % Exit the loop to start reading data
    end
end

% Parse and store the data
while ~feof(fid)
    line = fgetl(fid); % Read the next line

    if isempty(line) || isequal(line, -1)
        break; % End of file or empty line, break the loop
    end
    spaceIndex = strfind(line,' ');
    if ~isempty(spaceIndex)
        line(spaceIndex(1)) = [];
    end

    line = regexprep(line, '[-()\#\.\*]', '');
    % line = regexprep(line, '[\ SR]','_SR');
    % Split the line into components
    parts = strsplit(line);

    % Extract and process the parts
    valueName = parts{1};
    valueName = regexprep(valueName, '[\ ', '');
    averageValue = str2double(parts{2});
    errEstimate = str2double(parts{3});
    rmsdValue = str2double(parts{4});
    totalDrift = str2double(parts{5});
    unit = erase(parts{6}, '()'); % Remove parentheses

    % Store in the struct
    data.(valueName) = struct('Average', averageValue, ...
        'Err', errEstimate, ...
        'RMSD', rmsdValue, ...
        'TotalDrift', totalDrift, ...
        'Unit',regexprep(unit,'[()]',''));
end

% Close the file
fclose(fid);
end
